import smtplib
import os
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from loguru import logger
from dotenv import load_dotenv

from incident_model import IncidentReport

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
EMAIL_FROM = os.getenv("EMAIL_FROM", "")
EMAIL_TO = os.getenv("EMAIL_TO", "")

def send_incident_report_email(report: IncidentReport) -> bool:
    """
    Sends the incident report via email.
    Returns True if successful, False otherwise.
    """
    if not all([SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_FROM, EMAIL_TO]):
        logger.warning("Email configuration incomplete. Skipping email.")
        return False

    try:
        msg = MIMEMultipart()
        msg["From"] = EMAIL_FROM
        msg["To"] = EMAIL_TO
        msg["Subject"] = f"Incident Report: {report.dispatch_info.incident_type or 'Unknown Type'} - {report.dispatch_info.incident_number or 'New'}"

        # Create a formatted body
        body = f"""
        <html>
        <body>
            <h2>Incident Report</h2>
            <hr>
            <h3>Dispatch Information</h3>
            <ul>
                <li><strong>Incident Number:</strong> {report.dispatch_info.incident_number}</li>
                <li><strong>Date/Time:</strong> {report.dispatch_info.date_time}</li>
                <li><strong>Address:</strong> {report.dispatch_info.address}</li>
                <li><strong>Type:</strong> {report.dispatch_info.incident_type}</li>
                <li><strong>Priority:</strong> {report.dispatch_info.priority_level}</li>
            </ul>
            
            <h3>General Details</h3>
            <p><strong>Description:</strong> {report.general_details.description_of_events}</p>
            <p><strong>Scene:</strong> {report.general_details.scene_description}</p>
            <p><strong>Evidence/Property:</strong> {report.general_details.evidence_property}</p>
            
            <h4>Involved Parties</h4>
            <ul>
        """
        
        for person in report.general_details.involved_parties:
            body += f"<li><strong>{person.name or 'Unknown'}</strong> ({person.role or 'Unknown'}): {person.contact_info or 'N/A'}</li>"
            
        body += """
            </ul>
            <hr>
            <p><em>Generated by Gemini Native Dispatch Agent</em></p>
        </body>
        </html>
        """

        msg.attach(MIMEText(body, "html"))
        
        # Attach JSON version as well
        json_report = report.model_dump_json(indent=2)
        attachment = MIMEText(json_report, "json")
        attachment.add_header("Content-Disposition", "attachment", filename="incident_report.json")
        msg.attach(attachment)

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
            
        logger.info(f"Incident report email sent to {EMAIL_TO}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
